apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agro-app.fullname" . }}
  labels:
    {{- include "agro-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      {{- include "agro-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agro-app.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ .Values.metrics.path | default "/metrics" }}"
        prometheus.io/port: "{{ .Values.service.targetPort | default 5000 }}"
    spec:
      containers:
        - name: {{ include "agro-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: web
              containerPort: {{ .Values.service.targetPort | default 5000 }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath | default "/health" | quote }}
              port: web

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath | default "/health" | quote }}
              port: web


          env:
            - name: PORT
              value: "{{ .Values.service.targetPort | default 5000 }}"

          {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
