apiVersion: v1
kind: Service
metadata:
  name: {{ include "agro-app.fullname" . }}
  labels:
    {{- include "agro-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "agro-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 5000 }}
      protocol: TCP
