apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agro-app
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: agro-app
  endpoints:
    - port: web
      path: {{ .Values.metrics.path }}
      interval: 15s
